Repository shaunmillargov/ecrc-starter, pull requests merged in 2020-02, with the labels that each got.

#1 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, enhancement

#3 updated readme file
  src/ecrc-api/README.md
Labels: good first issue

#2 Setup frontend
  README.md
  src/Readme.txt
  src/ecrc-frontend/.eslintrc.js
  src/ecrc-frontend/.gitignore
  src/ecrc-frontend/.storybook/main.js
  src/ecrc-frontend/README.md
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/public/favicon.ico
  src/ecrc-frontend/public/index.html
  src/ecrc-frontend/public/logo192.png
  src/ecrc-frontend/public/logo512.png
  src/ecrc-frontend/public/manifest.json
  src/ecrc-frontend/public/robots.txt
  src/ecrc-frontend/src/App.js
  src/ecrc-frontend/src/index.css
  src/ecrc-frontend/src/index.js
  src/ecrc-frontend/src/serviceWorker.js
  src/ecrc-frontend/src/setupTests.js
  src/ecrc-frontend/yarn.lock
Labels: documentation, enhancement

#7 Jest GitHub actions
  .github/workflows/main.yml
  src/ecrc-frontend/package.json
Labels: enhancement

#18 Side card component
  src/ecrc-frontend/package-lock.json
  src/ecrc-frontend/package.json
  src/ecrc-frontend/src/components/base/sideCard/SideCard.css
  src/ecrc-frontend/src/components/base/sideCard/SideCard.js
  src/ecrc-frontend/src/components/base/sideCard/SideCard.stories.js
  src/ecrc-frontend/src/components/base/sideCard/SideCard.test.js
  src/ecrc-frontend/src/components/base/sideCard/__snapshots__/SideCard.test.js.snap
  src/ecrc-frontend/src/setupTests.js
Labels: enhancement

#20 Mvn Tests Github Action
  .github/workflows/main2.yml
Labels: enhancement

#33 Third side card
  src/ecrc-frontend/src/components/base/sideCard/SideCard.css
  src/ecrc-frontend/src/components/base/sideCard/SideCard.js
  src/ecrc-frontend/src/components/base/sideCard/SideCard.stories.js
  src/ecrc-frontend/src/components/base/sideCard/SideCard.test.js
Labels: enhancement
